### ISSUE TITLE
Is the only difference between `carpenter_build.yaml` and `carpenter_push.yaml` the addition of `--push` on lines 27 and 45?

### ISSUE THREAD

**Issue by portante** [arcalot/arcaflow-plugin-template-python#16]
Is the only difference between `carpenter_build.yaml` and `carpenter_push.yaml` the addition of `--push` on lines 27 and 45?

If so, isn't there a way to have the `carpenter_push.yaml` just use `carpenter_build.yaml` telling it to also use `--push`?  That would DRY it out.

_Originally posted by @portante in https://github.com/arcalot/arcaflow-plugin-template-python/pull/14#discussion_r1019385616_

**Comment by dustinblack** [comment]
This issue is obsolete after a number of recent changes.
